/*
 * Created on 23 dec 2015 (Time 08:53:38)
 * Generated by Telosys Tools Generator (version 2.1.1)
 */
package org.vasttrafik.wso2.carbon.community.api.dao.impl.jdbc;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

import org.vasttrafik.wso2.carbon.community.api.dao.ForumWatchDAO;
import org.vasttrafik.wso2.carbon.community.api.dao.impl.jdbc.commons.GenericDAO;
import org.vasttrafik.wso2.carbon.community.api.model.ForumWatchDTO;

/**
 * ForumWatchDTO DAO implementation 
 * 
 * @author Lars Andersson
 *
 */
public final class ForumWatchDAOImpl extends GenericDAO<ForumWatchDTO> implements ForumWatchDAO {

	private final static String SQL_SELECT = 
		"select com_id, com_forum_id, com_member_id from com_forum_watch where com_id = ?";

	private final static String SQL_INSERT = 
		"insert into com_forum_watch (com_forum_id, com_member_id) values (?, ?)";

	private final static String SQL_UPDATE = 
		"update com_forum_watch set com_forum_id = ?, com_member_id = ? where com_id = ?";

	private final static String SQL_DELETE = 
		"delete from com_forum_watch where com_id = ?";

	private final static String SQL_COUNT_ALL = 
		"select count(*) from com_forum_watch";

	private final static String SQL_COUNT = 
		"select count(*) from com_forum_watch where com_id = ?";

    //----------------------------------------------------------------------
	/**
	 * DAO constructor
	 */
	public ForumWatchDAOImpl() {
		super();
	}

	//----------------------------------------------------------------------
	/**
	 * Creates a new instance of the bean and populates it with the given primary value(s)
	 * @param id;
	 * @return the new instance
	 */
	private ForumWatchDTO newInstanceWithPrimaryKey(Long id) {
		ForumWatchDTO forumWatchDTO = new ForumWatchDTO();
		forumWatchDTO.setId(id);
		return forumWatchDTO ;
	}

	//----------------------------------------------------------------------
	/**
	 * Finds a bean by its primary key 
	 * @param id;
	 * @return the bean found or null if not found 
	 */
	@Override
	public ForumWatchDTO find(Long id) throws SQLException {
		ForumWatchDTO forumWatchDTO = newInstanceWithPrimaryKey(id) ;
		if (super.doSelect(forumWatchDTO)) {
			return forumWatchDTO ;
		}
		else {
			return null ; // Not found
		}
	}
	//----------------------------------------------------------------------
	/**
	 * Loads the given bean, it is supposed to contains the primary key value(s) in its attribute(s)<br>
	 * If found, the given instance is populated with the values retrieved from the database<br>
	 * If not found, the given instance remains unchanged
	 * @param forumWatchDTO
	 * @return true if found, false if not found
	 */
	@Override
	public boolean load(ForumWatchDTO forumWatchDTO) throws SQLException {
		return super.doSelect(forumWatchDTO) ;
	}
    //----------------------------------------------------------------------
	/**
	 * Inserts the given bean in the database 
	 * @param forumWatchDTO
	 */
	@Override
	public Long insert(ForumWatchDTO forumWatchDTO) throws SQLException {
		Long key = super.doInsertAutoIncr(forumWatchDTO);
		return key;
	}

    //----------------------------------------------------------------------
	/**
	 * Updates the given bean in the database 
	 * @param forumWatchDTO
	 * @return
	 */
	@Override
	public int update(ForumWatchDTO forumWatchDTO) throws SQLException {
		return super.doUpdate(forumWatchDTO);
	}	

    //----------------------------------------------------------------------
	/**
	 * Deletes the record in the database using the given primary key value(s) 
	 * @param id;
	 * @return
	 */
	@Override
	public int delete(Long id) throws SQLException {
		ForumWatchDTO forumWatchDTO = newInstanceWithPrimaryKey(id) ;
		return super.doDelete(forumWatchDTO);
	}

    //----------------------------------------------------------------------
	/**
	 * Deletes the given bean in the database 
	 * @param forumWatchDTO
	 * @return
	 */
	@Override
	public int delete(ForumWatchDTO forumWatchDTO) throws SQLException {
		return super.doDelete(forumWatchDTO);
	}

    //----------------------------------------------------------------------
	/**
	 * Checks the existence of a record in the database using the given primary key value(s)
	 * @param id;
	 * @return
	 */
	@Override
	public boolean exists(Long id) throws SQLException {
		ForumWatchDTO forumWatchDTO = newInstanceWithPrimaryKey(id) ;
		return super.doExists(forumWatchDTO);
	}
    //----------------------------------------------------------------------
	/**
	 * Checks the existence of the given bean in the database 
	 * @param forumWatchDTO
	 * @return
	 */
	@Override
	public boolean exists(ForumWatchDTO forumWatchDTO) throws SQLException {
		return super.doExists(forumWatchDTO);
	}

    //----------------------------------------------------------------------
	/**
	 * Counts all the records present in the database
	 * @return
	 */
	@Override
	public long count() throws SQLException {
		return super.doCountAll();
	}

    //----------------------------------------------------------------------
	@Override
	protected String getSqlSelect() {
		return SQL_SELECT ;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlInsert() {
		return SQL_INSERT ;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlUpdate() {
		return SQL_UPDATE ;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlDelete() {
		return SQL_DELETE ;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlCount() {
		return SQL_COUNT ;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlCountAll() {
		return SQL_COUNT_ALL ;
	}

    //----------------------------------------------------------------------
	@Override
	protected void setValuesForPrimaryKey(PreparedStatement ps, int i, ForumWatchDTO forumWatchDTO) throws SQLException {
		//--- Set PRIMARY KEY from bean to PreparedStatement (SQL "WHERE key=?, ...")
		setValue(ps, i++, forumWatchDTO.getId()) ; // "com_id" : java.lang.Integer
	}

    //----------------------------------------------------------------------
	@Override
	protected ForumWatchDTO populateBean(ResultSet rs, ForumWatchDTO forumWatchDTO) throws SQLException {
		//--- Set data from ResultSet to Bean attributes
		forumWatchDTO.setId(rs.getLong("com_id")); 				// java.lang.Long
		if (rs.wasNull()) { forumWatchDTO.setId(null); }; 		// not primitive number => keep null value if any
		forumWatchDTO.setForumId(rs.getInt("com_forum_id")); 	// java.lang.Integer
		if (rs.wasNull()) { forumWatchDTO.setForumId(null); }; 	// not primitive number => keep null value if any
		forumWatchDTO.setMemberId(rs.getInt("com_member_id")); 	// java.lang.Integer
		if (rs.wasNull()) { forumWatchDTO.setMemberId(null); }; // not primitive number => keep null value if any
		return forumWatchDTO ;
	}

    //----------------------------------------------------------------------
	@Override
	protected void setValuesForInsert(PreparedStatement ps, int i, ForumWatchDTO forumWatchDTO) throws SQLException {
		//--- Set PRIMARY KEY and DATA from bean to PreparedStatement (SQL "SET x=?, y=?, ...")
		// "com_id" is auto-incremented => no set in insert		
		setValue(ps, i++, forumWatchDTO.getForumId()) ; 		// "com_forum_id" : java.lang.Integer
		setValue(ps, i++, forumWatchDTO.getMemberId()) ; 		// "com_user_id" : java.lang.Integer
	}

    //----------------------------------------------------------------------
	@Override
	protected void setValuesForUpdate(PreparedStatement ps, int i, ForumWatchDTO forumWatchDTO) throws SQLException {
		//--- Set DATA from bean to PreparedStatement (SQL "SET x=?, y=?, ...")
		setValue(ps, i++, forumWatchDTO.getForumId()) ; 		// "com_forum_id" : java.lang.Integer
		setValue(ps, i++, forumWatchDTO.getMemberId()) ; 		// "com_user_id" : java.lang.Integer
		//--- Set PRIMARY KEY from bean to PreparedStatement (SQL "WHERE key=?, ...")
		setValue(ps, i++, forumWatchDTO.getId()) ; 				// "com_id" : java.lang.Long
	}
}
